import './style.css'
import './responsive.css'
import profilePhoto from './assets/ChatGPT Image Sep 23, 2026, 12_28_43 PM.png'
import backgroundVideo from './assets/5223113-hd_3840_2160_30fps.mp4'
// import Resume from'./asseets/Pathmapriya-Resume.txt'
const projects = [
  ['01','SpeakSafe','Mobile product','English Conversation & Speaking Practice App','A supportive mobile experience for building English confidence through guided speaking practice, grammar learning, level-based activities and AI-assisted conversations.',['UX Research'],'lavender','https://www.figma.com/proto/rqRvdisbGvkquiQguInH1a/Speaksafe---mobile-APP?t=d2Bxjt3SAQBGd5A4-1'],
  ['02','AI Image','Web experience','AI Image Generation Platform','A focused web experience for turning a written idea into a visual starting point through prompt creation, image generation, exploration and refinement.',['UX Research'],'sky','https://www.figma.com/proto/laIQfySby01j2RenjtUpX3/AI-Image---web?node-id=0-1&t=d2Bxjt3SAQBGd5A4-1']
]
const caseStudies = {
  '01': [
    ['Project Overview','A mobile English-learning product designed to help learners practise speaking in low-pressure, repeatable moments. The experience brings together guided lessons, grammar support, level-based progression and AI conversation practice.'],
    ['Problem Statement','Many learners understand written English but hesitate when speaking. Existing learning flows can feel intimidating, fragmented or too focused on right-or-wrong answers instead of confidence and repetition.'],
    ['User Research','The design direction is informed by common learner needs: short practice sessions, immediate but encouraging feedback, visible progress and conversation prompts that reduce the blank-page feeling.'],
    ['User Persona','An early-career learner who uses English at work, wants to speak more naturally and prefers practical practice that fits around a busy schedule.'],
    ['Pain Points','Fear of making mistakes, difficulty finding a starting prompt, unclear progress between lessons and a lack of feedback that feels constructive rather than corrective.'],
    ['Affinity Mapping','Insights were grouped around confidence, consistency, feedback and relevance. This pointed to a product structure that makes the next practice action obvious and celebrates small wins.'],
    ['User Flow','Open app → choose level → select a practice goal → review prompt → speak or respond → receive feedback → save progress → continue with the next activity.'],
    ['Information Architecture','Home, Learn, Practice, Progress and Profile create a simple navigation model. Practice stays central while supporting grammar and progress remain one tap away.'],
    ['Wireframes','Low-fidelity layouts explored lesson cards, conversation prompts, feedback states and progress summaries before visual styling was introduced.'],
    ['High-Fidelity UI','The final direction uses warm, approachable cards, clear hierarchy, friendly progress cues and focused conversation screens that keep attention on speaking.'],
    ['Prototype','The Figma prototype demonstrates onboarding, level selection, guided practice, AI conversation and feedback flows as one connected mobile journey.'],
    ['Final Solution','SpeakSafe turns a potentially intimidating activity into a calm daily ritual: choose a goal, practise in context, understand the feedback and see progress build.'],
    ['Design Impact','The concept gives learners a clearer reason to return, a more confident starting point and a consistent structure for turning practice into visible momentum.']
  ],
  '02': [
    ['Project Overview','An AI image-generation web experience that helps people move from a rough idea to a useful visual result without requiring advanced creative software skills.'],
    ['Problem Statement','New users often struggle to understand what to write, what the system can produce and how to improve an output. The interface needs to make experimentation feel approachable while keeping the creative controls discoverable.'],
    ['User Research','The experience is shaped around three recurring needs: a clear prompt starting point, fast visual feedback and an easy way to compare or revisit generated directions.'],
    ['User Persona','A marketer, designer or content creator who needs quick visual exploration for a campaign or concept and values speed, control and a low learning curve.'],
    ['Pain Points','Prompt uncertainty, unclear generation states, too many controls too early, difficulty comparing results and losing useful images during exploration.'],
    ['Affinity Mapping','Needs cluster around create, guide, compare and save. These themes become the backbone of a focused workspace rather than a tool-heavy dashboard.'],
    ['User Flow','Enter workspace → write or refine prompt → choose optional style settings → generate → review variations → refine prompt → save or export the selected image.'],
    ['Information Architecture','Create, Gallery, Explore and Account keep the primary action visible while allowing users to return to previous work and discover inspiration.'],
    ['Wireframes','Early layouts tested the prompt composer, generation state, result grid and image detail view so the key action stayed visible at every stage.'],
    ['High-Fidelity UI','The visual system balances a quiet workspace with expressive image results, using clear controls, generous preview space and strong contrast for the creation path.'],
    ['Prototype','The Figma prototype covers prompt entry, generation feedback, result selection, image refinement and saving a finished direction.'],
    ['Final Solution','AI Image is framed as a creative partner: it guides the first prompt, makes iteration understandable and keeps the best outputs close at hand.'],
    ['Design Impact','The concept reduces the distance between idea and visual exploration, helping first-time users start quickly while giving experienced users room to refine.']
  ]
}
const tagHTML = tags => tags.map(tag => `<span>${tag}</span>`).join('')
const visual = project => `<div class="project-visual visual-${project[6]}"><div class="visual-topline"><span class="mini-mark">${project[1][0]}</span><span>${project[2]}</span><span>•••</span></div><div class="visual-content"><strong>${project[1]}</strong><em>${project[3].split(' ').slice(0,3).join(' ')}</em><div class="visual-lines"><i></i><i></i><i></i></div></div><div class="visual-panels"><i></i><i></i><i></i></div></div>`
const projectHTML = projects.map(project => `<article class="project-card reveal" data-project="${project[0]}">${visual(project)}<div class="project-body"><div class="project-meta"><span>Project ${project[0]}</span><span>${project[2]}</span></div><h3>${project[1]}</h3><p>${project[4]}</p><div class="tags">${tagHTML(project[5])}</div><div class="project-actions"><button class="text-button">View Case Study ↗</button><a class="prototype-link" href="${project[7]}" target="_blank" rel="noreferrer">Open Figma Prototype ↗</a></div></div></article>`).join('')
const skillGroups = [['UI/UX Design','⌁',['Figma','Adobe XD','Wireframing','Prototyping','User Flow','Design Systems','Responsive Design','Usability Testing']],['Development','◌',['HTML','CSS','JavaScript','React','Bootstrap']],['Graphic Design','✦',['Adobe Photoshop','Adobe Illustrator','CorelDRAW']]]
const skillsHTML = skillGroups.map(group => `<div class="skill-card reveal"><b class="skill-icon">${group[1]}</b><h3>${group[0]}</h3><p>Building useful experiences with intention.</p><div class="chips">${tagHTML(group[2])}</div></div>`).join('')
const processHTML = [['01','Research'],['02','Define'],['03','Ideate'],['04','Wireframe'],['05','Design'],['06','Prototype'],['07','Test']].map(step => `<div><b>${step[0]}</b><i></i><h3>${step[1]}</h3><p>Understand, explore and make the next move clearer.</p></div>`).join('')
const responsibilities = ['Social media creatives','Branding and visual identity','Logo design','Marketing materials','Digital creatives','Client requirements','Photoshop / Illustrator / CorelDRAW'].map(item => `<span>↗ ${item}</span>`).join('')
const toolsHTML = ['Figma','Adobe XD','Ps','Ai','Corel','HTML','CSS','JS','React','Bs'].map(item => `<div><b>${item}</b><small>${item}</small></div>`).join('')
const infoHTML = ['Graphic Design'].map(item => `<div><b>✦</b><strong>${item}</strong><small>Thoughtful and useful</small></div>`).join('')

document.querySelector('#app').innerHTML = `
<video class="background-video" autoplay muted loop playsinline aria-hidden="true"><source src="${backgroundVideo}" type="video/mp4"></video><div class="background-video-overlay" aria-hidden="true"></div>
<header class="site-header"><div class="nav-wrap"><a class="brand" href="#home"><b>P</b>Pathmapriya<span>.</span></a><button class="menu-toggle" aria-label="Open menu">☰</button><nav><a href="#home">Home</a><a href="#about">About</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav><a class="button dark nav-cta" href="#contact">Let's Talk ↗</a></div></header><main>
<section id="home" class="hero section"><div class="container hero-grid"><div class="hero-copy reveal"><small class="eyebrow">● Available for select opportunities</small><h1>Hi, I'm <span>Pathmapriya</span>.<br><strong>UI/UX Designer crafting<br>simple, meaningful<br>digital experiences.</strong></h1><p>I design intuitive user experiences and visually engaging interfaces that connect users, brands and digital products.</p><div class="actions"><a class="button dark" href="#projects">View My Work ↗</a><button class="button light" id="resume">Download Resume ↓</button></div><div class="badges"><span>✦ UI/UX Design</span><span>⌁ Graphic Design</span></div></div><div class="hero-art reveal"><div class="portrait-frame"><img src="${profilePhoto}" alt="Pathmapriya, UI/UX Designer and Graphic Designer"><div class="portrait-caption"><small>DESIGNING WITH INTENT</small><strong>Thoughtful experiences,<br>made for people.</strong></div></div><div class="float profile">✦ <span>Current focus<br><b>Human-first products</b></span></div><div class="float note">P <span>UI/UX Designer<br><b>Visual thinker</b></span></div></div></div></section><div class="marquee" style="background:transparent"><span class="marquee-text">PRODUCT THINKING　✦　VISUAL CLARITY　✦　HUMAN CONNECTION　✦　PRODUCT THINKING</span></div>
<section id="about" class="section"><div class="container two-col"><small class="kicker">01　—　About me</small><div class="reveal"><h2>Design is how I make<br><em>complexity feel simple.</em></h2><p class="lead">I'm a passionate UI/UX and Graphic Designer focused on creating clean, intuitive and user-friendly digital experiences. With a background in graphic design, I combine visual creativity with UX thinking to transform ideas into meaningful digital products.</p><div class="about-bottom"><strong class="years">3<span>+</span></strong><span>Years of<br>design experience</span><div class="info-cards">${infoHTML}</div></div></div></div></section>
<section id="skills" class="section white"><div class="container"><div class="section-intro"><small class="kicker">02　—　Skills & toolkit</small><h2>The craft behind<br><em>the clarity.</em></h2><p>From first question to final pixel, I bring structure, curiosity and visual taste to every part of the process.</p></div><div class="skills-grid">${skillsHTML}</div></div></section>
<section id="projects" class="section"><div class="container"><small class="kicker">03　—　Selected work</small><div class="section-heading"><h2>Two projects,<br><em>thoughtfully shaped.</em></h2><p>Explore the product thinking, interaction design and visual systems behind my selected Figma prototypes.</p></div><div class="projects-grid">${projectHTML}</div></div></section>
<section class="section dark-section"><div class="container"><small class="kicker">04　—　Design process</small><h2>A rhythm for<br><em>good questions.</em></h2><div class="process">${processHTML}</div></div></section>
<section id="experience" class="section white"><div class="container two-col"><small class="kicker">05　—　Experience</small><div><h2>Graphic Designer</h2><p class="accent">2022 — Present · 3+ Years Experience</p><p class="lead">Creating visual identities and digital communication that make brands feel considered, memorable and ready for the real world.</p><div class="responsibilities">${responsibilities}</div><blockquote>“Combining my graphic design experience with UX thinking to create visually strong and user-focused digital experiences.”</blockquote></div></div></section>
<section class="tools section"><div class="container two-col"><div><small class="kicker">06　—　Tools I use</small><h2>Good work is<br><em>teamwork.</em></h2></div><div class="tool-grid">${toolsHTML}</div></div></section>
<section id="contact" class="contact section"><div class="container contact-grid"><div><small class="kicker">07　—　Let's connect</small><h2>Have a project or<br>opportunity in mind?</h2><h3>Let's create something <em>meaningful</em> together.</h3><div class="contact-links"><a href="mailto:pathmapriya@gmail.com">pathmapriya@gmail.com ↗</a><a href="tel:+919043927486">+91 90439 27486 ↗</a></div></div><form id="contact-form"><label>Name<input required placeholder="Your name"></label><label>Email<input required type="email" placeholder="you@email.com"></label><label>Subject<input required placeholder="What's on your mind?"></label><label>Message<textarea required rows="4" placeholder="Tell me a little about your project..."></textarea></label><button class="button light">Send Message ↗</button><p class="status"></p></form></div></section></main>
<footer><div class="container footer-grid"><div class="brand"><b>P</b>Pathmapriya<span>.</span><p>UI/UX Designer & Graphic Designer</p></div><div><small>Explore</small><a href="#about">About</a><a href="#projects">Projects</a><a href="#experience">Experience</a></div><div><small>Connect</small><a href="mailto:pathmapriya@gmail.com">pathmapriya@gmail.com</a><a href="tel:+919043927486">+91 90439 27486</a></div><div><small>Elsewhere</small><p>in　Be　Dr　Ig</p></div></div><div class="container footer-bottom">© 2026 Pathmapriya. All Rights Reserved.<span>Designed with intention ✦</span></div></footer><div class="modal" id="modal"><div class="modal-card"><button class="close">×</button><small class="kicker">CASE STUDY</small><h2 id="modal-title">SpeakSafe</h2><p id="modal-description"></p><div id="modal-tags" class="tags"></div><div id="case-sections" class="case-sections"></div></div></div>`

document.querySelector('.portrait-caption')?.remove()
document.querySelectorAll('.hero-art .float').forEach(element => element.remove())

const modal = document.querySelector('#modal')
document.addEventListener('click', event => { const card = event.target.closest('.project-card'); if (card && !event.target.closest('a')) { const project = projects.find(item => item[0] === card.dataset.project); document.querySelector('#modal-title').textContent = project[1]; document.querySelector('#modal-description').textContent = project[4]; document.querySelector('#modal-tags').innerHTML = tagHTML(project[5]); document.querySelector('#case-sections').innerHTML = caseStudies[project[0]].map((section, index) => `<div><small>${String(index + 1).padStart(2,'0')}</small><h3>${section[0]}</h3><p>${section[1]}</p></div>`).join(''); modal.classList.add('open') } if (event.target.closest('.close') || event.target === modal) modal.classList.remove('open') })
document.querySelector('#resume').addEventListener('click', () => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob(['PATHMAPRIYA\nUI/UX Designer & Graphic Designer\n\nPhone: +91 90439 27486\nEmail: pathmapriya@gmail.com\n\n3+ Years Design Experience'], {type:'text/plain'})); link.download = './assets/Pathmapriya_Resume.pdf'; link.click() })
document.querySelector('#contact-form').addEventListener('submit', event => { event.preventDefault(); event.currentTarget.querySelector('.status').textContent = 'Thanks - your message is ready to send.'; event.currentTarget.reset() })
document.querySelector('.menu-toggle').addEventListener('click', () => document.querySelector('nav').classList.toggle('open'))
const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('visible') }), {threshold:.1}); document.querySelectorAll('.reveal').forEach(element => observer.observe(element))
